apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-mysql-deployment
  labels:
    app: ubuntu-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-mysql
  template:
    metadata:
      labels:
        app: ubuntu-mysql
    spec:
      containers:
        - name: ubuntu
          image: ubuntu:20.04
          command: ["sleep"]
          args: ["infinity"]
          volumeMounts:
            - name: shared-data
              mountPath: /data
        
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootpass123
            - name: MYSQL_DATABASE
              value: testdb
            - name: MYSQL_USER
              value: testuser
            - name: MYSQL_PASSWORD
              value: testpass123
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql


      volumes:
        - name: mysql-data
          emptyDir: {}
        - name: shared-data
          emptyDir: {}
